<?php

########################################################################
# Extension Manager/Repository config file for ext: "nbogallery"
#
# Auto generated by Extension Builder 2012-03-30
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Gallery',
	'description' => 'Simple Gallery',
	'category' => 'plugin',
	'author' => 'Noel Bossart',
	'author_email' => 'n.company@me.com',
	'author_company' => 'sagenja.ch',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>